### ISSUE TITLE
Lost connection at the end of copy table

### ISSUE THREAD

**Issue by fpietka** [the4thdoctor/pg_chameleon#105]
Hi,

I'm having an issue running the `refresh_schema` command:

```
chameleon refresh_schema --config default --source mysql --schema ac --debug
```
After copying a 3Gb table I have the following error:
`Lost connection to MySQL server during query`

And here are the log I have just before it fails:
```
2019-10-25 07:14:13 MainProcess DEBUG mysql_lib.py (590): unlocking the table ac.company
2019-10-25 07:14:13 MainProcess INFO mysql_lib.py (703): Could not copy the table company. Excluding it from the replica.
2019-10-25 07:14:13 MainProcess DEBUG mysql_lib.py (304): Dropping the schema _public_tmp.
2019-10-25 07:14:13 MainProcess DEBUG pg_lib.py (658): Changing the lock timeout for the session to 120s.
2019-10-25 07:14:14 MainProcess CRITICAL mysql_lib.py (831): refresh schema ac for source mysql failed
```
I set `connect_timeout` to `600` (and it fails after 2 minutes or so), and `copy_max_memory` even down to `5M`.

It is not even my biggest table (which is around 55Gb). So I'm wondering what I am missing.

I'm using Mysql (percona) 5.7 and Postgres 11.

Thanks in advance for your help.

**Comment by fdalesio** [comment]
Similar problem here.
On some tables (not so big, 1gb or so), it fails on UNLOCK TABLES immediately after the copy.

Here's the logs:
```

2019-10-29 08:42:52 MainProcess INFO mysql_lib.py (644): Table hl_rendicontazione.allegato copied 4 slice of 5
2019-10-29 08:42:52 MainProcess INFO mysql_lib.py (644): Table hl_rendicontazione.allegato copied 5 slice of 5
2019-10-29 08:42:52 MainProcess DEBUG mysql_lib.py (590): unlocking the table hl_rendicontazione.allegato
2019-10-29 08:42:52 MainProcess INFO mysql_lib.py (703): Could not copy the table allegato. Excluding it from the replica.
2019-10-29 08:42:52 MainProcess DEBUG mysql_lib.py (304): Dropping the schema _posta_tmp.
2019-10-29 08:42:52 MainProcess DEBUG pg_lib.py (658): Changing the lock timeout for the session to 240s.
2019-10-29 08:42:53 MainProcess DEBUG mysql_lib.py (304): Dropping the schema _opendata_tmp.
2019-10-29 08:42:53 MainProcess DEBUG pg_lib.py (658): Changing the lock timeout for the session to 240s.
2019-10-29 08:42:53 MainProcess DEBUG mysql_lib.py (304): Dropping the schema _monitor_tmp.
2019-10-29 08:42:53 MainProcess DEBUG pg_lib.py (658): Changing the lock timeout for the session to 240s.
2019-10-29 08:42:53 MainProcess DEBUG mysql_lib.py (304): Dropping the schema _backup_tmp.
2019-10-29 08:42:53 MainProcess DEBUG pg_lib.py (658): Changing the lock timeout for the session to 240s.
2019-10-29 08:42:53 MainProcess DEBUG mysql_lib.py (304): Dropping the schema _datimonitor_tmp.
2019-10-29 08:42:53 MainProcess DEBUG pg_lib.py (658): Changing the lock timeout for the session to 240s.
2019-10-29 08:42:53 MainProcess DEBUG mysql_lib.py (304): Dropping the schema _rendicontazione_tmp.
2019-10-29 08:42:53 MainProcess DEBUG pg_lib.py (658): Changing the lock timeout for the session to 240s.
2019-10-29 08:42:53 MainProcess CRITICAL mysql_lib.py (1400): init replica for source mysql failed
Traceback (most recent call last):
  File "/home/halleylombardia/chamaleon/venv/lib/python3.6/site-packages/pymysql/connections.py", line 713, in _write_bytes
    self._sock.sendall(data)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/halleylombardia/chamaleon/venv/bin/chameleon", line 5, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/halleylombardia/chamaleon/venv/bin/chameleon.py", line 58, in <module>
    getattr(replica, args.command)()
  File "/home/halleylombardia/chamaleon/venv/lib/python3.6/site-packages/pg_chameleon/lib/global_lib.py", line 327, in init_replica
    self.__init_mysql_replica()
  File "/home/halleylombardia/chamaleon/venv/lib/python3.6/site-packages/pg_chameleon/lib/global_lib.py", line 337, in __init_mysql_replica
    self.mysql_source.init_replica()
  File "/home/halleylombardia/chamaleon/venv/lib/python3.6/site-packages/pg_chameleon/lib/mysql_lib.py", line 1381, in init_replica
    self.__copy_tables()
  File "/home/halleylombardia/chamaleon/venv/lib/python3.6/site-packages/pg_chameleon/lib/mysql_lib.py", line 699, in __copy_tables
    master_status = self.copy_data(schema, table)
  File "/home/halleylombardia/chamaleon/venv/lib/python3.6/site-packages/pg_chameleon/lib/mysql_lib.py", line 592, in copy_data
    self.cursor_buffered.execute(sql_unlock)
  File "/home/halleylombardia/chamaleon/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/halleylombardia/chamaleon/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/halleylombardia/chamaleon/venv/lib/python3.6/site-packages/pymysql/connections.py", line 516, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/home/halleylombardia/chamaleon/venv/lib/python3.6/site-packages/pymysql/connections.py", line 771, in _execute_command
    self._write_bytes(packet)
  File "/home/halleylombardia/chamaleon/venv/lib/python3.6/site-packages/pymysql/connections.py", line 718, in _write_bytes
    "MySQL server has gone away (%r)" % (e,))
pymysql.err.OperationalError: (2006, "MySQL server has gone away (ConnectionResetError(104, 'Connection reset by peer'))")

```
> 

I'm on MySQL 5.7 (Azure) and PostgreSQL 10.10

**Comment by the4thdoctor** [comment]
it may be a permission issue? what are the source's user grants?

**Comment by fpietka** [comment]
Grants in my case:
```
 GRANT RELOAD, LOCK TABLES, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'usr_replica'@'%'
```

Since it fails on some table, what kind of difference are we looking for?

**Comment by the4thdoctor** [comment]
I would look at the permissions for those tables. in #65 the problem was caused by wrong permissions.
could be useful also to have what mysql logs when the unlock fails. 

Thanks

**Comment by fpietka** [comment]
Grants are on everything (`*.*`), or am I missing something?

**Comment by fpietka** [comment]
Here an example for a table that sometimes pass, some other don't:
```
2019-11-09T12:03:51.087431Z 44753194 [Note] InnoDB: Table `ac`.`bo_log` flushed to disk
2019-11-09T12:04:06.103961Z 44753194 [Note] Aborted connection 44753194 to db: 'unconnected' user: 'usr_replica' host: 'postgres-replica-1.c.xxxx.internal' (Got timeout reading communication packets)
2019-11-09T12:04:06.104223Z 44753194 [Note] InnoDB: Deleting the meta-data file './ac/bo_log.cfg'
2019-11-09T12:04:06.104246Z 44753194 [Note] InnoDB: Resuming purge
```

**Comment by the4thdoctor** [comment]
apparently is a connection timeout. did you try to increase the connect timeout to a very large value?

**Comment by fpietka** [comment]
I've set `connect_timeout: 6000` and even `lock_timeout: "480s"`.

It fails after 3m43.316s

**Comment by the4thdoctor** [comment]
anything particular about this mysql db? 
it's self managed or it's on RDS or Azure?

**Comment by fpietka** [comment]
It's a percona server, and it is on GCE on a Debian (full root access).

**Comment by the4thdoctor** [comment]
I would dig into this post https://www.percona.com/blog/2016/05/16/mysql-got-an-error-reading-communication-packet-errors/

**Comment by odoucet** [comment]
If anyone get here with the same issue, we were able to solve it by setting `net_read_timeout=600` (from a default value of 30) on MySQL side. It cannot be changed on pg_chameleon directly though.

**Comment by the4thdoctor** [comment]
Apparently it's possible to set the parameter per session.
I can try to add it as connection parameter and manage the value before starting the copy.

e.g.
`SET SESSION   net_read_timeout = 600;`

I'm not sure I can add it to the next release though.
I'm reopening the issue as a reminder.
ta!

**Comment by the4thdoctor** [comment]
I've pushed the change to the main branch and will be part of the release 2.0.20. Each source now can have a parameter  net_read_timeout. if missing it defaults to 600.
Each mysql cursor sets the value of  net_read_timeout on connection for the session.
I wasn't able to reproduce the issue though.
