### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by killerwzb** [the4thdoctor/pg_chameleon#135]
Hi：

 I follow this https://pgchameleon.org/documents_v2/usage.html#example to install pg_chameleon.
 After i run this command:  chameleon set_configuration_files and throw the error like this:

(venv) [root@centos1 Python-3.6.6]# chameleon set_configuration_files 
Traceback (most recent call last):
  File "/usr/src/Python-3.6.6/venv/bin/chameleon", line 5, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/usr/src/Python-3.6.6/venv/bin/chameleon.py", line 5, in <module>
    from pg_chameleon import replica_engine
  File "/usr/src/Python-3.6.6/venv/lib/python3.6/site-packages/pg_chameleon/__init__.py", line 2, in <module>
    from .lib.mysql_lib import *
  File "/usr/src/Python-3.6.6/venv/lib/python3.6/site-packages/pg_chameleon/lib/mysql_lib.py", line 7, in <module>
    from pymysqlreplication import BinLogStreamReader
  File "/usr/src/Python-3.6.6/venv/lib/python3.6/site-packages/pymysqlreplication/__init__.py", line 23, in <module>
    from .binlogstream import BinLogStreamReader
  File "/usr/src/Python-3.6.6/venv/lib/python3.6/site-packages/pymysqlreplication/binlogstream.py", line 9, in <module>
    from pymysql.util import int2byte
ModuleNotFoundError: No module named 'pymysql.util'

**I check the pip list and get this:**
(venv) [root@centos1 Python-3.6.6]# pip list
Package           Version
----------------- ---------
certifi           2020.12.5
chardet           4.0.0
daemonize         2.5.0
idna              2.10
mysql-replication 0.23
pg-chameleon      2.0.16
pip               21.0.1
psycopg2-binary   2.8.6
PyMySQL           1.0.2
PyYAML            5.4.1
requests          2.25.1
rollbar           0.15.2
setuptools        39.0.1
six               1.15.0
tabulate          0.8.7
urllib3           1.26.3

**Can you tell how to resolve it ?
thanks.**

**Comment by marvincorreia** [comment]
The installation is Ok, but the pg_chameleon is not compatible with PyMySQL==1.0.2
Try this on your terminal:
```
pip uninstall PyMySQL
pip install "PyMySQL==0.9.3"
```

**Comment by killerwzb** [comment]
I have resloved it ,thanks.

**Comment by killerwzb** [comment]
I have resloved it ,thanks.
