### ISSUE TITLE
Incorrect parsing of CREATE TABLE statement

### ISSUE THREAD

**Issue by zambodaniel** [the4thdoctor/pg_chameleon#138]
**Describe the bug**
Init replica fails with the following error:
`2021-06-16 13:07:58 MainProcess ERROR global_lib.py (568): Stack trace: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pg_chameleon/lib/pg_lib.py", line 2783, in get_data_type
    type_override = self.type_override[column["column_type"]]
KeyError: 'típus'`

**To Reproduce**
Create a source database with the following table, and start replication:
`CREATE TABLE `report_product_stocks` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `server_id` int unsigned NOT NULL,
  `stock_type_id` int unsigned NOT NULL,
  `product_id` int unsigned NOT NULL,
  `transaction_date` date NOT NULL,
  `amount_net` decimal(18,2) NOT NULL DEFAULT '0.00',
  `amount_purchase` decimal(18,2) NOT NULL DEFAULT '0.00',
  `quantity` decimal(18,2) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`,`transaction_date`),
  UNIQUE KEY `idx_last_stock` (`product_id`,`stock_type_id`,`server_id`,`transaction_date`),
  KEY `idx_cleanup` (`transaction_date`,`created_at`) USING BTREE,
  KEY `idx_composite` (`transaction_date`,`product_id`,`stock_type_id`,`server_id`) USING BTREE,
  KEY `idx_composite_product` (`product_id`,`transaction_date`,`stock_type_id`,`server_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=356010256 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Termék készlet kirendeltség, készlet típus szinten, napi bontásban'
/*!50500 PARTITION BY RANGE  COLUMNS(transaction_date)
(PARTITION p0 VALUES LESS THAN ('2000-01-01') ENGINE = InnoDB,
 PARTITION p1 VALUES LESS THAN ('2001-01-01') ENGINE = InnoDB,
 PARTITION p2 VALUES LESS THAN ('2002-01-01') ENGINE = InnoDB,
 PARTITION p3 VALUES LESS THAN ('2003-01-01') ENGINE = InnoDB,
 PARTITION p4 VALUES LESS THAN ('2004-01-01') ENGINE = InnoDB,
 PARTITION p5 VALUES LESS THAN ('2005-01-01') ENGINE = InnoDB,
 PARTITION p6 VALUES LESS THAN ('2006-01-01') ENGINE = InnoDB,
 PARTITION p7 VALUES LESS THAN ('2007-01-01') ENGINE = InnoDB,
 PARTITION p8 VALUES LESS THAN ('2008-01-01') ENGINE = InnoDB,
 PARTITION p9 VALUES LESS THAN ('2009-01-01') ENGINE = InnoDB,
 PARTITION p10 VALUES LESS THAN ('2010-01-01') ENGINE = InnoDB,
 PARTITION p11 VALUES LESS THAN ('2011-01-01') ENGINE = InnoDB,
 PARTITION p12 VALUES LESS THAN ('2012-01-01') ENGINE = InnoDB,
 PARTITION p13 VALUES LESS THAN ('2013-01-01') ENGINE = InnoDB,
 PARTITION p14 VALUES LESS THAN ('2014-01-01') ENGINE = InnoDB,
 PARTITION p15 VALUES LESS THAN ('2015-01-01') ENGINE = InnoDB,
 PARTITION p16 VALUES LESS THAN ('2016-01-01') ENGINE = InnoDB,
 PARTITION p17 VALUES LESS THAN ('2017-01-01') ENGINE = InnoDB,
 PARTITION p18 VALUES LESS THAN ('2018-01-01') ENGINE = InnoDB,
 PARTITION p19 VALUES LESS THAN ('2019-01-01') ENGINE = InnoDB,
 PARTITION p20 VALUES LESS THAN (MAXVALUE) ENGINE = InnoDB) */`

**Expected behavior**
Should not parse COMMENT

**Screenshots**

**Environment:**
 - pg-chameleon: 2.0.16
 - OS: Debian GNU/Linux 10 (buster)
 - MySQL Version 8.0.23-14 (percona)
 - PostgreSQL Version 13.2 (Debian 13.2-1.pgdg100+1)
 - Python Version 3.7.3

**Additional context**

**Comment by zambodaniel** [comment]
Full log:
`2021-06-16 13:07:57 read_replica DEBUG mysql_lib.py (1291): TOKEN: {'command': 'CREATE TABLE', 'name': 'report_product_stocks', 'columns': [{'column_name': 'id', 'data_type': 'int', 'is_nullable': 'NO', 'extra': 'auto_increment', 'column_
type': 'int'}, {'column_name': 'server_id', 'data_type': 'int', 'is_nullable': 'NO', 'extra': '', 'column_type': 'int'}, {'column_name': 'stock_type_id', 'data_type': 'int', 'is_nullable': 'NO', 'extra': '', 'column_type': 'int'}, {'colum
n_name': 'product_id', 'data_type': 'int', 'is_nullable': 'NO', 'extra': '', 'column_type': 'int'}, {'column_name': 'transaction_date', 'data_type': 'date', 'is_nullable': 'NO', 'extra': '', 'column_type': 'date'}, {'column_name': 'amount_net', 'data_type': 'decimal', 'is_nullable': 'NO', 'enum_list': '( 18, 2 )', 'character_maximum_length': '18, 2', 'numeric_precision': '18', 'numeric_scale': '2', 'extra': '', 'column_type': 'decimal(18, 2)'}, {'column_name': 'amount_purchase', 'data_type': 'decimal', 'is_nullable': 'NO', 'enum_list': '( 18, 2 )', 'character_maximum_length': '18, 2', 'numeric_precision': '18', 'numeric_scale': '2', 'extra': '', 'column_type': 'decimal(18, 2)'}, {'column_name': 'quantity', 'data_type': 'decimal', 'is_nullable': 'NO', 'enum_list': '( 18, 2 )', 'character_maximum_length': '18, 2', 'numeric_precision': '18', 'numeric_scale': '2', 'extra': '', 'column_type': 'decimal(18, 2)'}, {'column_name': 'created_at', 'data_type': 'timestamp', 'is_nullable': 'YES', 'extra': 'auto_increment', 'column_type': 'timestamp'}, {'column_name': 'készlet', 'data_type': 'típus', 'is_nullable': 'YES', 'extra': '', 'column_type': 'típus'}, {'column_name': 'napi', 'data_type': 'bontásban', 'is_nullable': 'YES', 'enum_list': '( transaction_date )', 'character_maximum_length': 'transaction_date', 'numeric_precision': 'transaction_date', 'numeric_scale': 0, 'extra': '', 'column_type': 'bontásban(transaction_date)'}, {'column_name': 'PARTITION', 'data_type': 'p1', 'is_nullable': 'YES', 'enum_list': "( '2001-01-01' )", 'character_maximum_length': "'2001-01-01'", 'numeric_precision': "'2001-01-01'", 'numeric_scale': 0, 'extra': '', 'column_type': "p1('2001-01-01')"}, {'column_name': 'PARTITION', 'data_type': 'p2', 'is_nullable': 'YES', 'enum_list': "( '2002-01-01' )", 'character_maximum_length': "'2002-01-01'", 'numeric_precision': "'2002-01-01'", 'numeric_scale': 0, 'extra': '', 'column_type': "p2('2002-01-01')"}, {'column_name': 'PARTITION', 'data_type': 'p3', 'is_nullable': 'YES', 'enum_list': "( '2003-01-01' )", 'character_maximum_length': "'2003-01-01'", 'numeric_precision': "'2003-01-01'", 'numeric_scale': 0, 'extra': '', 'column_type': "p3('2003-01-01')"}, {'column_name': 'PARTITION', 'data_type': 'p4', 'is_nullable': 'YES', 'enum_list': "( '2004-01-01' )", 'character_maximum_length': "'2004-01-01'", 'numeric_precision': "'2004-01-01'", 'numeric_scale': 0, 'extra': '', 'column_type': "p4('2004-01-01')"}, {'column_name': 'PARTITION', 'data_type': 'p5', 'is_nullable': 'YES', 'enum_list': "( '2005-01-01' )", 'character_maximum_length': "'2005-01-01'", 'numeric_precision': "'2005-01-01'", 'numeric_scale': 0, 'extra': '', 'column_type': "p5('2005-01-01')"}, {'column_name': 'PARTITION', 'data_type': 'p6', 'is_nullable': 'YES', 'enum_list': "( '2006-01-01' )", 'character_maximum_length': "'2006-01-01'", 'numeric_precision': "'2006-01-01'", 'numeric_scale': 0, 'extra': '', 'column_type': "p6('2006-01-01')"}, {'column_name': 'PARTITION', 'data_type': 'p7', 'is_nullable': 'YES', 'enum_list': "( '2007-01-01' )", 'character_maximum_length': "'2007-01-01'", 'numeric_precision': "'2007-01-01'", 'numeric_scale': 0, 'extra': '', 'column_type': "p7('2007-01-01')"}, {'column_name': 'PARTITION', 'data_type': 'p8', 'is_nullable': 'YES', 'enum_list': "( '2008-01-01' )", 'character_maximum_length': "'2008-01-01'", 'numeric_precision': "'2008-01-01'", 'numeric_scale': 0, 'extra': '', 'column_type': "p8('2008-01-01')"}, {'column_name': 'PARTITION', 'data_type': 'p9', 'is_nullable': 'YES', 'enum_list': "( '2009-01-01' )", 'character_maximum_length': "'2009-01-01'", 'numeric_precision': "'2009-01-01'", 'numeric_scale': 0, 'extra': '', 'column_type': "p9('2009-01-01')"}, {'column_name': 'PARTITION', 'data_type': 'p10', 'is_nullable': 'YES', 'enum_list': "( '2010-01-01' )", 'character_maximum_length': "'2010-01-01'", 'numeric_precision': "'2010-01-01'", 'numeric_scale': 0, 'extra': '', 'column_type': "p10('2010-01-01')"}, {'column_name': 'PARTITION', 'data_type': 'p11', 'is_nullable': 'YES', 'enum_list': "( '2011-01-01' )", 'character_maximum_length': "'2011-01-01'", 'numeric_precision': "'2011-01-01'", 'numeric_scale': 0, 'extra': '', 'column_type': "p11('2011-01-01')"}, {'column_name': 'PARTITION', 'data_type': 'p12', 'is_nullable': 'YES', 'enum_list': "( '2012-01-01' )", 'character_maximum_length': "'2012-01-01'", 'numeric_precision': "'2012-01-01'", 'numeric_scale': 0, 'extra': '', 'column_type': "p12('2012-01-01')"}, {'column_name': 'PARTITION', 'data_type': 'p13', 'is_nullable': 'YES', 'enum_list': "( '2013-01-01' )", 'character_maximum_length': "'2013-01-01'", 'numeric_precision': "'2013-01-01'", 'numeric_scale': 0, 'extra': '', 'column_type': "p13('2013-01-01')"}, {'column_name': 'PARTITION', 'data_type': 'p14', 'is_nullable': 'YES', 'enum_list': "( '2014-01-01' )", 'character_maximum_length': "'2014-01-01'", 'numeric_precision': "'2014-01-01'", 'numeric_scale': 0, 'extra': '', 'column_type': "p14('2014-01-01')"}, {'column_name': 'PARTITION', 'data_type': 'p15', 'is_nullable': 'YES', 'enum_list': "( '2015-01-01' )", 'character_maximum_length': "'2015-01-01'", 'numeric_precision': "'2015-01-01'", 'numeric_scale': 0, 'extra': '', 'column_type': "p15('2015-01-01')"}, {'column_name': 'PARTITION', 'data_type': 'p16', 'is_nullable': 'YES', 'enum_list': "( '2016-01-01' )", 'character_maximum_length': "'2016-01-01'", 'numeric_precision': "'2016-01-01'", 'numeric_scale': 0, 'extra': '', 'column_type': "p16('2016-01-01')"}, {'column_name': 'PARTITION', 'data_type': 'p17', 'is_nullable': 'YES', 'enum_list': "( '2017-01-01' )", 'character_maximum_length': "'2017-01-01'", 'numeric_precision': "'2017-01-01'", 'numeric_scale': 0, 'extra': '', 'column_type': "p17('2017-01-01')"}, {'column_name': 'PARTITION', 'data_type': 'p18', 'is_nullable': 'YES', 'enum_list': "( '2018-01-01' )", 'character_maximum_length': "'2018-01-01'", 'numeric_precision': "'2018-01-01'", 'numeric_scale': 0, 'extra': '', 'column_type': "p18('2018-01-01')"}, {'column_name': 'PARTITION', 'data_type': 'p19', 'is_nullable': 'YES', 'enum_list': "( '2019-01-01' )", 'character_maximum_length': "'2019-01-01'", 'numeric_precision': "'2019-01-01'", 'numeric_scale': 0, 'extra': '', 'column_type': "p19('2019-01-01')"}, {'column_name': 'PARTITION', 'data_type': 'p20', 'is_nullable': 'YES', 'enum_list': '( MAXVALUE )', 'character_maximum_length': 'MAXVALUE', 'numeric_precision': 'MAXVALUE', 'numeric_scale': 0, 'extra': '', 'column_type': 'p20(MAXVALUE)'}], 'indices': [{'index_name': 'PRIMARY', 'index_columns': ['id', 'transaction_date'], 'non_unique': 0}, {'index_name': 'ukidx_report_product_stock_0', 'index_columns': ['product_id', 'stock_type_id', 'server_id', 'transaction_date'], 'non_unique': 0}, {'index_name': 'idx_report_product_stock_1', 'index_columns': ['transaction_date', 'created_at'], 'non_unique': 1}, {'index_name': 'idx_report_product_stock_2', 'index_columns': ['transaction_date', 'product_id', 'stock_type_id', 'server_id'], 'non_unique': 1}, {'index_name': 'idx_report_product_stock_3', 'index_columns': ['product_id', 'transaction_date', 'stock_type_id', 'server_id'], 'non_unique': 1}]}
2021-06-16 13:07:58 MainProcess ERROR global_lib.py (567): Read process alive: False - Replay process alive: True
2021-06-16 13:07:58 MainProcess ERROR global_lib.py (568): Stack trace: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pg_chameleon/lib/pg_lib.py", line 2783, in get_data_type
    type_override = self.type_override[column["column_type"]]
KeyError: 'típus'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pg_chameleon/lib/global_lib.py", line 496, in read_replica
    self.mysql_source.read_replica()
  File "/usr/local/lib/python3.7/dist-packages/pg_chameleon/lib/mysql_lib.py", line 1453, in read_replica
    replica_data=self.__read_replica_stream(batch_data)
  File "/usr/local/lib/python3.7/dist-packages/pg_chameleon/lib/mysql_lib.py", line 1301, in __read_replica_stream
    self.pg_engine.write_ddl(token, query_data, destination_schema)
  File "/usr/local/lib/python3.7/dist-packages/pg_chameleon/lib/pg_lib.py", line 1957, in write_ddl
    pg_ddl = self.__generate_ddl(token, destination_schema)
  File "/usr/local/lib/python3.7/dist-packages/pg_chameleon/lib/pg_lib.py", line 1315, in __generate_ddl
    table_ddl = self.__build_create_table_mysql(table_metadata,  table_name,  destination_schema, temporary_schema=False)
  File "/usr/local/lib/python3.7/dist-packages/pg_chameleon/lib/pg_lib.py", line 2422, in __build_create_table_mysql
    column_type = self.get_data_type(column, schema, table_name)
  File "/usr/local/lib/python3.7/dist-packages/pg_chameleon/lib/pg_lib.py", line 2791, in get_data_type
    column_type = self.type_dictionary[column["data_type"]]
KeyError: 'típus'
2021-06-16 13:07:58 MainProcess ERROR global_lib.py (574): Read daemon crashed. Terminating the replay daemon.
2021-06-16 13:07:58 MainProcess DEBUG pg_lib.py (659): Changing the autocommit flag to True
2021-06-16 13:07:58 MainProcess INFO global_lib.py (599): Replica process for source mysql ended`

**Comment by zambodaniel** [comment]
Works with python 3.9.5
