### ISSUE TITLE
mysql to postgres start replica does not stay running

### ISSUE THREAD

**Issue by firdoze1234** [the4thdoctor/pg_chameleon#140]
**Describe the bug**
Once the mysql to postgres replica is initialized, I get this error almost immediately when I start the replica:

2022-02-23 11:44:55 MainProcess INFO: init replica for source mysql is complete
2022-02-23 12:14:34 MainProcess INFO: Checking if the replica for source mysql is stopped
2022-02-23 12:14:34 MainProcess INFO: Cleaning not processed batches for source mysql
2022-02-23 12:14:34 MainProcess INFO: Starting the replica daemons for source mysql
2022-02-23 12:14:44 MainProcess ERROR: Read process alive: False - Replay process alive: True
2022-02-23 12:14:44 MainProcess ERROR: Stack trace: Traceback (most recent call last):
  File "/home/postgres/.local/lib/python3.6/site-packages/pg_chameleon/lib/global_lib.py", line 500, in read_replica
    self.mysql_source.read_replica()
  File "/home/postgres/.local/lib/python3.6/site-packages/pg_chameleon/lib/mysql_lib.py", line 1464, in read_replica
    replica_data=self.__read_replica_stream(batch_data)
  File "/home/postgres/.local/lib/python3.6/site-packages/pg_chameleon/lib/mysql_lib.py", line 1230, in __read_replica_stream
    for binlogevent in my_stream:
  File "/home/postgres/.local/lib/python3.6/site-packages/pymysqlreplication/binlogstream.py", line 505, in fetchone
    self.__fail_on_table_metadata_unavailable)
  File "/home/postgres/.local/lib/python3.6/site-packages/pymysqlreplication/packet.py", line 143, in __init__
    fail_on_table_metadata_unavailable=fail_on_table_metadata_unavailable)
  File "/home/postgres/.local/lib/python3.6/site-packages/pymysqlreplication/event.py", line 197, in __init__
    self._read_status_vars_value_for_key(status_vars_key)
  File "/home/postgres/.local/lib/python3.6/site-packages/pymysqlreplication/event.py", line 262, in _read_status_vars_value_for_key
    db = self.packet.read_string()
  File "/home/postgres/.local/lib/python3.6/site-packages/pymysqlreplication/packet.py", line 481, in read_string
    char = self.read(1)
  File "/home/postgres/.local/lib/python3.6/site-packages/pymysqlreplication/packet.py", line 157, in read
    return self.packet.read(size)
  File "/home/postgres/.local/lib/python3.6/site-packages/pymysql/protocol.py", line 74, in read
    raise AssertionError(error)
AssertionError: Result length not requested length:
Expected=1.  Actual=0.  Position: 74.  Data Length: 74

2022-02-23 12:14:44 MainProcess ERROR: Read daemon crashed. Terminating the replay daemon.
2022-02-23 12:14:44 MainProcess INFO: Replica process for source mysql ended

**To Reproduce**
 ~/.local/bin/chameleon start_replica --config migration --source mysql

**Expected behavior**
Expect replica to stay running

**Screenshots**

**Environment(please complete the following information):**
 - OS: Red Hat Enterprise Linux Server release 7.9 (Maipo)
 - MySQL Version: 5.7.35
 - PostgreSQL Version: 12.9
 - Python Version: 3.6
 - Cloud hosted database: NA 

**Additional context**

**Comment by the4thdoctor** [comment]
hi, I've found a similar issue caused by a regression in the mysql-replica library. 
I'll make a new release soon forcing the mysql-replication<0.27.
can you try to run `pip install "mysql-replication<0.26"` and check if the problem is solved?
thanks

**Comment by firdoze1234** [comment]
That fixed the issue, the replica started and is consistent. Thank you!

**Comment by the4thdoctor** [comment]
Thanks for your feedback. I'll make a new release this week to solve the issue.
