### ISSUE TITLE
MySQL read daemon fails with decoding error

### ISSUE THREAD

**Issue by ldesgoui** [the4thdoctor/pg_chameleon#141]
**Describe the bug**
When following the example usage from the documentation, when running `chameleon start_replica`, the program will fail with `LookupError: unknown encoding: utf8mb3` (Full log attached below).

**To Reproduce**
- Run MariaDB and PostgreSQL containers using the Docker Compose
- Create a table and insert rows in MariaDB
- Follow the [usage example](https://www.pgchameleon.org/documents/usage.html#example)

**Expected behavior**
The replication starts successfully.

**Environment(please complete the following information):**
 - OS: NixOS + Docker
 - MySQL Version: 10.6.5-MariaDB-1:10.6.5+maria~focal-log
 - PostgreSQL Version: 13.6
 - Python Version: 3.9.6

**Additional context**

<details>

```
2022-02-26 00:26:14 MainProcess DEBUG pg_lib.py (660): Changing the autocommit flag to True
2022-02-26 00:26:14 MainProcess DEBUG pg_lib.py (660): Changing the autocommit flag to True
2022-02-26 00:26:14 MainProcess DEBUG pg_lib.py (660): Changing the autocommit flag to True
2022-02-26 00:26:14 MainProcess INFO global_lib.py (617): Checking if the replica for source mysql is stopped
2022-02-26 00:26:14 MainProcess INFO global_lib.py (627): Cleaning not processed batches for source mysql
2022-02-26 00:26:14 MainProcess DEBUG pg_lib.py (3239): Cleaning table t_log_replica_mysql_1
2022-02-26 00:26:14 MainProcess DEBUG pg_lib.py (3239): Cleaning table t_log_replica_mysql_2
2022-02-26 00:26:14 MainProcess INFO global_lib.py (558): Starting the replica daemons for source mysql
2022-02-26 00:26:14 MainProcess DEBUG global_lib.py (567): Replica process for source mysql is running
2022-02-26 00:26:14 MainProcess DEBUG pg_lib.py (660): Changing the autocommit flag to True
2022-02-26 00:26:14 read_replica DEBUG pg_lib.py (660): Changing the autocommit flag to True
2022-02-26 00:26:14 replay_replica DEBUG pg_lib.py (660): Changing the autocommit flag to True
2022-02-26 00:26:14 MainProcess DEBUG pg_lib.py (1277): Cleaning replayed batches for source mysql older than 1 day
2022-02-26 00:26:14 read_replica DEBUG pg_lib.py (680): There is already a database connection active.
2022-02-26 00:26:14 read_replica DEBUG pg_lib.py (3111): Collecting schema mappings for source mysql
2022-02-26 00:26:14 read_replica DEBUG mysql_lib.py (1463): Batch data [(12, 'mysql-bin.000003', 469495347, 't_log_replica_mysql_1', None)]
2022-02-26 00:26:14 read_replica DEBUG mysql_lib.py (1011): collecting table type map
2022-02-26 00:26:14 read_replica DEBUG mysql_lib.py (1228): GTID DISABLED - log_file mysql-bin.000003, log_position 469495347. id_batch: 12
2022-02-26 00:26:14 read_replica DEBUG mysql_lib.py (1242): ROTATE EVENT - binlogfile mysql-bin.000003, position 469495347.
2022-02-26 00:26:15 MainProcess ERROR global_lib.py (571): Read process alive: False - Replay process alive: True
2022-02-26 00:26:15 MainProcess ERROR global_lib.py (572): Stack trace: Traceback (most recent call last):
  File "/home/ldesgoui/db/rewrite/venv/lib/python3.9/site-packages/pg_chameleon/lib/global_lib.py", line 500, in read_replica
    self.mysql_source.read_replica()
  File "/home/ldesgoui/db/rewrite/venv/lib/python3.9/site-packages/pg_chameleon/lib/mysql_lib.py", line 1464, in read_replica
    replica_data=self.__read_replica_stream(batch_data)
  File "/home/ldesgoui/db/rewrite/venv/lib/python3.9/site-packages/pg_chameleon/lib/mysql_lib.py", line 1322, in __read_replica_stream
    for row in binlogevent.rows:
  File "/home/ldesgoui/db/rewrite/venv/lib/python3.9/site-packages/pymysqlreplication/row_event.py", line 443, in rows
    self._fetch_rows()
  File "/home/ldesgoui/db/rewrite/venv/lib/python3.9/site-packages/pymysqlreplication/row_event.py", line 438, in _fetch_rows
    self.__rows.append(self._fetch_one_row())
  File "/home/ldesgoui/db/rewrite/venv/lib/python3.9/site-packages/pymysqlreplication/row_event.py", line 491, in _fetch_one_row
    row["values"] = self._read_column_data(self.columns_present_bitmap)
  File "/home/ldesgoui/db/rewrite/venv/lib/python3.9/site-packages/pymysqlreplication/row_event.py", line 138, in _read_column_data
    values[name] = self.__read_string(2, column)
  File "/home/ldesgoui/db/rewrite/venv/lib/python3.9/site-packages/pymysqlreplication/row_event.py", line 234, in __read_string
    string = string.decode(encoding)
LookupError: unknown encoding: utf8mb3

2022-02-26 00:26:15 MainProcess ERROR global_lib.py (578): Read daemon crashed. Terminating the replay daemon.
2022-02-26 00:26:15 MainProcess DEBUG pg_lib.py (660): Changing the autocommit flag to True
2022-02-26 00:26:15 MainProcess INFO global_lib.py (603): Replica process for source mysql ended

```

```yaml
# Docker Compose
version: '3'
services:
  postgres:
    image: postgres:13
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: dbname
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
    restart: always
    ports:
      - "5432:5432"
  mysql:
    image: mariadb
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql-config:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: dbname
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    restart: always
    ports:
      - "3306:3306"
```

```ini
[mariadbd]
binlog_format = ROW
binlog_row_image = full
log-bin = mysql-bin
server-id = 1
expire_logs_days = 10
```

```yaml
---
# global settings
pid_dir: ~/.pg_chameleon/pid/
log_dir: ~/.pg_chameleon/logs/
log_dest: file
log_level: info
log_days_keep: 10
rollbar_key: ''
rollbar_env: ''

# type_override allows the user to override the default type conversion
# into a different one.

type_override:
  'tinyint(1)':
    override_to: boolean
    override_tables:
      - '*'


# postgres  destination connection
pg_conn:
  host: localhost
  port: 5432
  user: user
  password: password
  database: dbname
  charset: utf8

sources:
  mysql:
    type: mysql
    db_conn:
      host: localhost
      port: 3306
      user: user
      password: password
      charset: utf8
      connect_timeout: 10
    schema_mappings:
      dbname: archive_wp
    limit_tables: []
    skip_tables: []
    grant_select_to: []
    lock_timeout: 120s
    my_server_id: 1
    replica_batch_size: 10000
    replay_max_rows: 10000
    batch_retention: 1 day
    copy_max_memory: 300M
    copy_mode: file
    out_dir: /tmp
    sleep_loop: 1
    on_error_replay: continue
    on_error_read: continue
    auto_maintenance: disabled
    gtid_enable: false
    skip_events:
      insert: []
      delete: []
      update: []
    keep_existing_schema: true
```

```
MariaDB [(none)]> show variables like 'char%'; show variables like 'collation%';
+--------------------------+----------------------------+
| Variable_name            | Value                      |
+--------------------------+----------------------------+
| character_set_client     | utf8mb3                    |
| character_set_connection | utf8mb3                    |
| character_set_database   | utf8mb4                    |
| character_set_filesystem | binary                     |
| character_set_results    | utf8mb3                    |
| character_set_server     | utf8mb4                    |
| character_set_system     | utf8mb3                    |
| character_sets_dir       | /usr/share/mysql/charsets/ |
+--------------------------+----------------------------+
8 rows in set (0.001 sec)

+----------------------+--------------------+
| Variable_name        | Value              |
+----------------------+--------------------+
| collation_connection | utf8mb3_general_ci |
| collation_database   | utf8mb4_unicode_ci |
| collation_server     | utf8mb4_unicode_ci |
+----------------------+--------------------+
3 rows in set (0.000 sec)
```

**Comment by ldesgoui** [comment]
It works with `mysql` instead of `mariadb`, disregard :)
