### ISSUE TITLE
Error during self.pg_engine.cleanup_table_events()

### ISSUE THREAD

**Issue by dimoschi** [the4thdoctor/pg_chameleon#153]
**Describe the bug**
I get a bug when trying to sync a specific table.

```log
postgres@host:~/.pg_chameleon/configuration$ chameleon sync_tables --source mysql --tables academy.users --debug
2023-03-17 22:31:19 MainProcess DEBUG pg_lib.py (661): Changing the autocommit flag to True
2023-03-17 22:31:19 MainProcess DEBUG pg_lib.py (661): Changing the autocommit flag to True
2023-03-17 22:31:19 MainProcess INFO mysql_lib.py (996): Starting sync tables for source mysql
2023-03-17 22:31:19 MainProcess DEBUG pg_lib.py (661): Changing the autocommit flag to True
2023-03-17 22:31:19 MainProcess DEBUG pg_lib.py (681): There is already a database connection active.
2023-03-17 22:31:19 MainProcess DEBUG pg_lib.py (3124): Collecting schema mappings for source mysql
2023-03-17 22:31:19 MainProcess DEBUG mysql_lib.py (1005): The tables affected are academy.users
2023-03-17 22:31:19 MainProcess DEBUG mysql_lib.py (310): Creating the loading schema _db_replica_tmp.
2023-03-17 22:31:19 MainProcess DEBUG mysql_lib.py (312): Creating the destination schema db_replica.
2023-03-17 22:31:19 MainProcess INFO pg_lib.py (873): Granting select on tables in schema _db_replica_tmp to the role(s) postgres.
2023-03-17 22:31:19 MainProcess DEBUG pg_lib.py (661): Changing the autocommit flag to False
2023-03-17 22:31:19 MainProcess DEBUG pg_lib.py (661): Changing the autocommit flag to True
2023-03-17 22:31:19 MainProcess DEBUG mysql_lib.py (323): Dropping the schema _db_replica_tmp.
2023-03-17 22:31:19 MainProcess DEBUG pg_lib.py (699): Changing the lock timeout for the session to 120s.
2023-03-17 22:31:19 MainProcess INFO pg_lib.py (3445): Set high watermark for source: mysql
2023-03-17 22:31:19 MainProcess DEBUG pg_lib.py (1935): Cleaning up log events in log table t_log_replica_mysql_1
2023-03-17 22:31:19 MainProcess DEBUG mysql_lib.py (323): Dropping the schema _db_replica_tmp.
2023-03-17 22:31:19 MainProcess DEBUG pg_lib.py (699): Changing the lock timeout for the session to 120s.
2023-03-17 22:31:19 MainProcess CRITICAL mysql_lib.py (1038): the sync for tables academy.users in source mysql failed
Traceback (most recent call last):
  File "/usr/local/bin/chameleon", line 5, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/usr/local/bin/chameleon.py", line 58, in <module>
    getattr(replica, args.command)()
  File "/usr/local/lib/python3.8/dist-packages/pg_chameleon/lib/global_lib.py", line 431, in sync_tables
    self.mysql_source.sync_tables()
  File "/usr/local/lib/python3.8/dist-packages/pg_chameleon/lib/mysql_lib.py", line 1028, in sync_tables
    self.pg_engine.cleanup_table_events()
  File "/usr/local/lib/python3.8/dist-packages/pg_chameleon/lib/pg_lib.py", line 1937, in cleanup_table_events
    self.pgsql_cur.execute(sql_clean_log)
psycopg2.errors.SyntaxError: syntax error at or near ")"
LINE 1: ..._1" WHERE format('%I.%I',v_schema_name,v_table_name) IN () ;
```

**To Reproduce**
On a Ubuntu 20.04 machine that runs both MariaDB 10.3.38 and PostgreSQL 12.14
1. Created the `default.yml` based on the example config file.
2. Created a replication user in MariaDB and a user in PostgreSQL
3. Initialized the replica with:
```sh
chameleon create_replica_schema --debug
chameleon add_source --config default --source mysql --debug
chameleon init_replica --config default  --source mysql --debug
```
4. Running `chameleon sync_tables --source mysql --tables academy.users --debug` produces the error above.

**Expected behavior**
The expected behaviour is to sync the requested table. On another machine with the exact same environment (OS, DBs, etc.) the replication works fine for almost 2 weeks not.

**Screenshots**
```yml
# postgres  destination connection
pg_conn:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: ""
  database: "db_replica"
  charset: "utf8"

sources:
  mysql:
    db_conn:
      host: "localhost"
      port: "3306"
      user: "usr_replica"
      password: ""
      charset: 'utf8'
      connect_timeout: 10
    schema_mappings:
      academy: academy
    limit_tables:
    skip_tables:
    grant_select_to:
    lock_timeout: "120s"
    my_server_id: 212
    replica_batch_size: 10000
    replay_max_rows: 10000
    batch_retention: '1 day'
    copy_max_memory: "300M"
    copy_mode: 'file'
    out_dir: /tmp
    sleep_loop: 1
    on_error_replay: exit
    on_error_read: exit
    auto_maintenance: "disabled"
    gtid_enable: false
    type: mysql
    keep_existing_schema: No
```

**Environment(please complete the following information):**
 - OS: Ubuntu 22.04
 - MariaDB 10.3.38
 - PostgreSQL 12.14
 - Python 3.8.10

**Additional context**

**Comment by dimoschi** [comment]
I managed to solve it by granting all permissions and then removing them one by one. The problem is with the permissions required on the MariaDB side. The user required the `SELECT` and `LOCK TABLES` permissions to `init_replica`.

**Comment by the4thdoctor** [comment]
On the documentation I've put a grant requirement for the replica user
`GRANT ALL ON sakila.* TO 'usr_replica';`
I reckon this may be too much for the scope. I'll give a try to your suggestion and eventually I'll update the documentation.
Thanks
