### ISSUE TITLE
Replica initialization fails with "IndexError: tuple index out of range"

### ISSUE THREAD

**Issue by markosutic** [the4thdoctor/pg_chameleon#166]
**Describe the bug**
Replica initialization fails with error:
```
[2023-08-18T12:30:41.958Z] [0;32m    2023-08-18 12:30:28 MainProcess INFO: Adding constraint and indices to the destination table  testusr1.table1[0m
[2023-08-18T12:30:41.958Z] [0;32m    2023-08-18 12:30:28 MainProcess INFO: Creating the primary key tab_pkey[0m
[2023-08-18T12:30:41.958Z] [0;32m    2023-08-18 12:30:28 MainProcess INFO: Creating the index ix_tab_utr[0m
[2023-08-18T12:30:41.958Z] [0;32m    2023-08-18 12:30:28 MainProcess INFO: Creating the index tab_loc_fk[0m
[2023-08-18T12:30:41.958Z] [0;32m    2023-08-18 12:30:28 MainProcess INFO: Creating the index utr_idx[0m
2023-08-16 10:04:13 MainProcess CRITICAL mysql_lib.py (1585): init replica for source mysql failed
Traceback (most recent call last):
  File "/var/lib/pgsql/pg_chameleon_venv/bin/chameleon", line 5, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/var/lib/pgsql/pg_chameleon_venv/bin/chameleon.py", line 58, in <module>
    getattr(replica, args.command)()
  File "/var/lib/pgsql/pg_chameleon_venv/lib64/python3.6/site-packages/pg_chameleon/lib/global_lib.py", line 357, in init_replica
    self.__init_mysql_replica()
  File "/var/lib/pgsql/pg_chameleon_venv/lib64/python3.6/site-packages/pg_chameleon/lib/global_lib.py", line 367, in __init_mysql_replica
    self.mysql_source.init_replica()
  File "/var/lib/pgsql/pg_chameleon_venv/lib64/python3.6/site-packages/pg_chameleon/lib/mysql_lib.py", line 1570, in init_replica
    self.pg_engine.save_master_status(master_start)
  File "/var/lib/pgsql/pg_chameleon_venv/lib64/python3.6/site-packages/pg_chameleon/lib/pg_lib.py", line 3476, in save_master_status
    master_data = master_status[0]
IndexError: tuple index out of range
```

**To Reproduce**
Issue cannot be reproduced. It is appearing only for a single MySQL instance. The same initialization works on other stands.

**Expected behavior**
Initialization to complete.

**Environment(please complete the following information):**
 - OS: Centos7
 - MySQL 5.6.51
 - PostgreSQL Version 11
 - Python Version 3.6
 - pg_chameleon 2.0.19

**Additional context**
We have tried to run `drop_replica_schema` and repeat initialization but didn't helped. Also tried to downgrade pg_chameleon to 2.0.18 without success also.

**Config**

We use `limit_tables` to migrate 3 tables with `keep_existing_schema: Yes`.

Can you please what can be done to troubleshoot or fix issue.

Thanks

Best regards,
Marko

**Comment by markosutic** [comment]
Hi!

Root cause of the issue was corrupted binary log or binary log index.
Closing ticket.

Best regards,
Marko
