### ISSUE TITLE
psycopg2.errors.UndefinedTable: relation "sch_chameleon.t_sources" does not exist

### ISSUE THREAD

**Issue by monkir** [the4thdoctor/pg_chameleon#170]
OS: ubuntu 22.04
python: 3.10.12

MySql and Postgresql connection are ok. But I got these error.

```shell
(migration) monkir@mypg:~/.pg_chameleon/configuration$ chameleon start_replica --config migration --source mysql
Traceback (most recent call last):
  File "/home/monkir/Desktop/migration/bin/chameleon", line 5, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/monkir/Desktop/migration/bin/chameleon.py", line 56, in <module>
    replica = replica_engine(args)
  File "/home/monkir/Desktop/migration/lib/python3.10/site-packages/pg_chameleon/lib/global_lib.py", line 165, in __init__
    source_count = self.pg_engine.check_source()
  File "/home/monkir/Desktop/migration/lib/python3.10/site-packages/pg_chameleon/lib/pg_lib.py", line 2249, in check_source
    self.pgsql_cur.execute(sql_check, (self.source, ))
psycopg2.errors.UndefinedTable: relation "sch_chameleon.t_sources" does not exist
LINE 5:                 sch_chameleon.t_sources
                        ^
```

**Comment by the4thdoctor** [comment]
probably you didn't run the create replica schema. I'll add a control on the replica to get rid of the error.

**Comment by the4thdoctor** [comment]
I've just pushed the change for a nice error message when the replica schema is missing.
It will appear in the next release.
