### ISSUE TITLE
Documentation is unclear

### ISSUE THREAD

**Issue by moolight-seashell** [the4thdoctor/pg_chameleon#174]
The documentation doesn't seem very clear to me,

I've already had a bit of trouble finding this page :
https://pgchameleon.org/documents/usage.html#example

some lines are not executable as is,
but most of all I'm stuck here:
```bash
$ chameleon add_source --config default
/home/team/.local/bin/chameleon.py:2: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import get_distribution
You must specify a source name with the argument --source

$chameleon add_source --config default --source example
/home/team/.local/bin/chameleon.py:2: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import get_distribution
Traceback (most recent call last):
  File "/home/team/.local/bin/chameleon", line 5, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/team/.local/bin/chameleon.py", line 61, in <module>
    getattr(replica, args.command)()
  File "/home/team/.local/lib/python3.12/site-packages/pg_chameleon/lib/global_lib.py", line 301, in add_source
    self.pg_engine.add_source()
  File "/home/team/.local/lib/python3.12/site-packages/pg_chameleon/lib/pg_lib.py", line 2264, in add_source
    check_mappings = self.check_schema_mappings()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/team/.local/lib/python3.12/site-packages/pg_chameleon/lib/pg_lib.py", line 2198, in check_schema_mappings
    schema_mappings = json.dumps(self.sources[self.source]["schema_mappings"])
                                 ~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'example'
```

**Comment by the4thdoctor** [comment]
wham mysql version are you using?

for the create user and database it's just an example that should work as a starting point.

**Comment by moolight-seashell** [comment]
for this particular task I used mysql 5

thanks for the feedback.

in any case the database i tried to migrate could not be migrated automatically due to its complexity.
there were too many procedures and so on.

**Comment by dgleba** [comment]
I did a lot of work to create this example.

(https://github.com/dgleba/732collection/tree/main/red74/uptimekuma-623_yard/mysql2pg_pg_chameleon/pg-cham-683b)

It runs in docker compose on ubuntu.

Maybe it could help you.
