### ISSUE TITLE
Error in version 1.6. Can't start init_replica

### ISSUE THREAD

**Issue by alexshnup** [the4thdoctor/pg_chameleon#23]
Traceback (most recent call last):
  File "/usr/local/bin/chameleon.py", line 50, in <module>
    replica.init_replica()
  File "/usr/local/lib/python3.6/site-packages/pg_chameleon/lib/global_lib.py", line 255, in init_replica
    self.pg_eng.set_source_id('initialising')
  File "/usr/local/lib/python3.6/site-packages/pg_chameleon/lib/pg_lib.py", line 279, in set_source_id
    self.pg_conn.pgsql_cur.execute(sql_source, (source_status, source_name))
psycopg2.ProgrammingError: relation "sch_chameleon.t_sources" does not exist
LINE 2:    UPDATE sch_chameleon.t_sources

**Comment by the4thdoctor** [comment]
can you please tell me the steps for reproducing the error?

**Comment by alexshnup** [comment]
Sorry.  It's ok.  Problem in my postgress schema.

**Comment by the4thdoctor** [comment]
cool :)
