### ISSUE TITLE
error in "get_data_type"

### ISSUE THREAD

**Issue by Hoya** [the4thdoctor/pg_chameleon#73]
This is the latest crash error I have, could you take a look?

Thanks.

```
--------
ALTER TABLE `service_estimation_category` ADD COLUMN `visibility` bool DEFAULT 0 NOT NULL
-------- 
2018-05-11 16:47:30 read_replica DEBUG mysql_lib.py (1008): TOKEN: {'command': 'ALTER TABLE', 'alter_cmd': [{'column_type': 'bool  0', 'dimension': 0, 'default': None, 'data_type': 'bool  0', 'command': 'ADD', 'type': 'bool  0', 'name': 'visibility'}], 'name': 'service_estimation_category'}
2018-05-11 16:47:30 replay_replica INFO pg_lib.py (1228): Cleaning replayed batches for source mysql older than 1 day
2018-05-11 16:47:31 MainProcess ERROR global_lib.py (532): Read process alive: False - Replay process alive: True
2018-05-11 16:47:31 MainProcess ERROR global_lib.py (533): Stack trace: Traceback (most recent call last):
  File "/root/pg_chameleon/venv/lib/python3.5/site-packages/pg_chameleon/lib/pg_lib.py", line 2662, in get_data_type
    type_override = self.type_override[column["column_type"]]
KeyError: 'bool  0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/pg_chameleon/venv/lib/python3.5/site-packages/pg_chameleon/lib/global_lib.py", line 480, in read_replica
    self.mysql_source.read_replica()
  File "/root/pg_chameleon/venv/lib/python3.5/site-packages/pg_chameleon/lib/mysql_lib.py", line 1155, in read_replica
    replica_data=self.__read_replica_stream(batch_data)
  File "/root/pg_chameleon/venv/lib/python3.5/site-packages/pg_chameleon/lib/mysql_lib.py", line 1018, in __read_replica_stream
    self.pg_engine.write_ddl(token, query_data, destination_schema)
  File "/root/pg_chameleon/venv/lib/python3.5/site-packages/pg_chameleon/lib/pg_lib.py", line 1876, in write_ddl
    pg_ddl = self.__generate_ddl(token, destination_schema)
  File "/root/pg_chameleon/venv/lib/python3.5/site-packages/pg_chameleon/lib/pg_lib.py", line 1289, in __generate_ddl
    query=self.build_alter_table(destination_schema, token)
  File "/root/pg_chameleon/venv/lib/python3.5/site-packages/pg_chameleon/lib/pg_lib.py", line 1402, in build_alter_table
    column_type=self.get_data_type(alter_dic, schema, table_name)
  File "/root/pg_chameleon/venv/lib/python3.5/site-packages/pg_chameleon/lib/pg_lib.py", line 2670, in get_data_type
    column_type = self.type_dictionary[column["data_type"]]
KeyError: 'bool  0'

2018-05-11 16:47:31 MainProcess ERROR global_lib.py (539): Read daemon crashed. Terminating the replay daemon.
2018-05-11 16:47:31 MainProcess DEBUG pg_lib.py (616): Changing the autocommit flag to True
2018-05-11 16:47:31 MainProcess ERROR global_lib.py (55): Could not send the message to rollbar.
2018-05-11 16:47:31 MainProcess INFO global_lib.py (550): Replica process for source mysql ended
```

**Comment by the4thdoctor** [comment]
hi, thanks for the report. 
yes, this is an issue I've found several times and is related to the way the regular expression tokenise the statement. 

I'll try to sort out the problem asap.

**Comment by the4thdoctor** [comment]
can you test the last commit please? 
my tests show the issue should be fixed.

thanks

**Comment by the4thdoctor** [comment]
ok, seems to work. can you please do a git pull on the branch ver2.0 and test it?

**Comment by Hoya** [comment]
Sorry about the late response. I've excluded the tables that have issues for now. I'll make sure to test it once you release a build, thanks.

**Comment by the4thdoctor** [comment]
Undestood, thanks. I'll do the release this sunday.
