### ISSUE TITLE
I'm having real trouble getting chameleon to actually do anything.

### ISSUE THREAD

**Issue by qlj** [the4thdoctor/pg_chameleon#85]
Hi,

The config is as follows:

---
#global settings
pid_dir: '~/.pg_chameleon/pid/'
log_dir: '~/.pg_chameleon/logs/'
log_dest: file
log_level: info
log_days_keep: 10
rollbar_key: ''
rollbar_env: ''

#type_override allows the user to override the default type conversion into a different one.
type_override:
  "tinyint(1)":
    override_to: boolean
    override_tables:
      - "*"

#postgres  destination connection
pg_conn:
  host: "localhost"
  port: "5432"
  user: "developer"
  password: "my_pg_password"
  database: "move_uat"
  charset: "utf8"

sources:
  mysql:
    db_conn:
      host: "10.0.0.166"
      port: "3306"
      user: "developer"
      password: "my_mysql_password"
      charset: 'utf8'
      connect_timeout: 10
    schema_mappings:
      public: public
    skip_tables:
    grant_select_to:
      - developer
    lock_timeout: "120s"
    my_server_id: 1
    replica_batch_size: 10000
    replay_max_rows: 10000
    batch_retention: '1 day'
    copy_max_memory: "300M"
    copy_mode: 'file'
    out_dir: /tmp
    sleep_loop: 15
    on_error_replay: continue
    on_error_read: continue
    auto_maintenance: "disabled"
    gtid_enable: No
    type: mysql

The commands I issue:

chameleon create_replica_schema
chameleon add_source --config default --source mysqlprovided in config yml
chameleon init_replica --source mysql

The response:

Init replica process for source mysql started.

When I issue the command: chameleon start_replica --source mysql
The response is : The replica process is already started or is syncing. Aborting the command.

**Comment by the4thdoctor** [comment]
You have to wait for the init replica to finish. Can you please run init replica with - -debug and post the output?
Thanks

**Comment by qlj** [comment]
root@FO-PGSQL01:~/.pg_chameleon/configuration# chameleon init_replica --debug
2018-08-16 10:40:41 MainProcess DEBUG pg_lib.py (617): Changing the autocommit flag to True
You must specify a source name with the argument --source

After this, I supplied the --source option as requested, and this is what follows:

root@FO-PGSQL01:~/.pg_chameleon/configuration# chameleon init_replica --debug --source mysql
2018-08-16 10:41:27 MainProcess DEBUG pg_lib.py (617): Changing the autocommit flag to True
2018-08-16 10:41:27 MainProcess DEBUG pg_lib.py (617): Changing the autocommit flag to True
2018-08-16 10:41:27 MainProcess DEBUG mysql_lib.py (1328): starting init replica for source mysql
2018-08-16 10:41:32 MainProcess DEBUG pg_lib.py (617): Changing the autocommit flag to True
2018-08-16 10:41:32 MainProcess DEBUG pg_lib.py (3029): Collecting schema mappings for source mysql
2018-08-16 10:41:32 MainProcess INFO pg_lib.py (1843): deleting all the table references from the replica catalog for source mysql
Traceback (most recent call last):
  File "/usr/local/bin/chameleon", line 5, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/usr/local/bin/chameleon.py", line 58, in <module>
    getattr(replica, args.command)()
  File "/usr/local/lib/python2.7/dist-packages/pg_chameleon/lib/global_lib.py", line 327, in init_replica
    self.__init_mysql_replica()
  File "/usr/local/lib/python2.7/dist-packages/pg_chameleon/lib/global_lib.py", line 337, in __init_mysql_replica
    self.mysql_source.init_replica()
  File "/usr/local/lib/python2.7/dist-packages/pg_chameleon/lib/mysql_lib.py", line 1335, in init_replica
    self.__build_table_exceptions()
  File "/usr/local/lib/python2.7/dist-packages/pg_chameleon/lib/mysql_lib.py", line 202, in __build_table_exceptions
    limit_tables = self.source_config["limit_tables"]
KeyError: 'limit_tables'

**Comment by qlj** [comment]
Hi Federico,

Thanks to your suggestion above I was illuminated by the debug statements to finally figure out the various stumbling blocks.  I'm having a timeout issue on large data, but I'll deal with that.  Thank you for your help.  The replicator is now working until it reaches too-big data.

**Comment by the4thdoctor** [comment]
you are using python 2.7. this system is compatible with python 3.3+ only. I suspect you downloaded the old version 1.8 which I'm no longer developing.

**Comment by the4thdoctor** [comment]
I suppose you were able to make it work. I'm closing the ticket
