### ISSUE TITLE
null values cannot be formatted as an SQL identifier

### ISSUE THREAD

**Issue by rahilsh** [the4thdoctor/pg_chameleon#86]
I tried replicating one test table with two columns(id and name) and a single row. When I update the name column in MySQL, I get below error and replication stops. Also, I get same error when I tried replicating actor table of sakila database(https://dev.mysql.com/doc/sakila/en/sakila-installation.html)

Below are the versions I am using:

mysql  Ver 14.14 Distrib 5.7.21, for osx10.12 (x86_64) using  EditLine wrapper
psql (PostgreSQL) 10.2
pg-chameleon 2.0.9

Logs:

```
2018-08-27 16:21:26 MainProcess INFO: Checking if the replica for source mysql is stopped
2018-08-27 16:21:48 MainProcess INFO: Checking if the replica for source mysql is stopped
2018-08-27 16:21:48 MainProcess INFO: Cleaning not processed batches for source mysql
2018-08-27 16:21:48 MainProcess INFO: Starting the replica daemons for source mysql
2018-08-27 16:21:58 MainProcess ERROR: Read process alive: True - Replay process alive: False
2018-08-27 16:21:58 MainProcess ERROR: Stack trace: Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pg_chameleon/lib/global_lib.py", line 503, in replay_replica
    tables_error = self.pg_engine.replay_replica()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pg_chameleon/lib/pg_lib.py", line 1164, in replay_replica
    self.pgsql_cur.execute(sql_replay, (replay_max_rows, self.i_id_source, exit_on_error))
psycopg2.DataError: null values cannot be formatted as an SQL identifier
CONTEXT:  PL/pgSQL function sch_chameleon.fn_replay_mysql(integer,integer,boolean) line 211 at FOR over EXECUTE statement


2018-08-27 16:21:58 MainProcess ERROR: Replay daemon crashed. Terminating the read daemon.
2018-08-27 16:21:58 MainProcess INFO: Replica process for source mysql ended
```

**Comment by the4thdoctor** [comment]
Thanks for reporting the bug, the issue appears to be postgresql 10 specific. 
postgresql 9.6 is not affected.
I'll work to a fix and release a new version asap.

**Comment by the4thdoctor** [comment]
Can you please run this test for me?
Install the version 2.0.9. When the process crashes load this updated function (it's already formatted to overwrite the one in sch_chameleon [https://pastebin.com/DJ2Den9S](https://pastebin.com/DJ2Den9S ).
The problem was caused by not filtering the  NULL value for the primary key before the formatting. 
PostgreSQL 9.6 didn't complain but the version 10 it seems it is more stringent in that sense.

If the function works as expected I'll run some tests and I'll do a new release this week end.

Thanks

**Comment by rahilsh** [comment]
@the4thdoctor I installed the latest chameleon and updated function, now I don't get any error but data is not replicated

**Comment by the4thdoctor** [comment]
This is the package with the fix (replay and json). Can you please test it?
[pg_chameleon-2.0.9.1.tar.gz](https://github.com/the4thdoctor/pg_chameleon/files/2331226/pg_chameleon-2.0.9.1.tar.gz)
